// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQPWAPr-S8yHLtIRN6AryveH5ln9hZMcE',
    appId: '1:562891858605:web:30946af5214569d119dc24',
    messagingSenderId: '562891858605',
    projectId: 'todoz-d4cf7',
    authDomain: 'todoz-d4cf7.firebaseapp.com',
    storageBucket: 'todoz-d4cf7.appspot.com',
    measurementId: 'G-DZSYBJ8BNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVueYbdcLhJ8JbI9X5C8u3gjFBf_MNjM',
    appId: '1:562891858605:android:6e5401870178b85b19dc24',
    messagingSenderId: '562891858605',
    projectId: 'todoz-d4cf7',
    storageBucket: 'todoz-d4cf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMNSP8SmUROqCbTPalM7q6pr_dmRXb2J8',
    appId: '1:562891858605:ios:135c3c0e7bb7c15919dc24',
    messagingSenderId: '562891858605',
    projectId: 'todoz-d4cf7',
    storageBucket: 'todoz-d4cf7.appspot.com',
    iosBundleId: 'com.example.listify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMNSP8SmUROqCbTPalM7q6pr_dmRXb2J8',
    appId: '1:562891858605:ios:3275b2c35114e5f819dc24',
    messagingSenderId: '562891858605',
    projectId: 'todoz-d4cf7',
    storageBucket: 'todoz-d4cf7.appspot.com',
    iosBundleId: 'com.example.listify.RunnerTests',
  );
}
